### PR TITLE
using .editorconfig for universal formatting.

### PR DESCRIPTION
**Pull request by MangeshPimpalkar**
editorconfig.org

### CODE REVIEW

**Comment by MangeshPimpalkar** [comment]
@VictorBjelkholm please review.

**Comment by MangeshPimpalkar** [comment]
Hi @VictorBjelkholm 
There are lots of PR waiting to be merged.

**Comment by cetra3** [comment]
@MangeshPimpalkar what will this add to the project?  Can you give us a rundown of why its necessary?

**Comment by MangeshPimpalkar** [comment]
@VictorBjelkholm Whenever PR is created the code is formatted according to the editors they are using eg Webstrom/sublime/eclipse have they their own code formatters.
.editorconfig makes the formatting consistent.Instead of using default editor formatters we use .editorconfig.
All the projects use it .angular/mean

**Pull request merged**
